-- init/init-database.sql

CREATE DATABASE "immigration-visa";

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"password" varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_username_key UNIQUE (username)
);



CREATE TABLE public.user_roles (
	role_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id)
);


-- public.user_roles foreign keys

ALTER TABLE public.user_roles ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(id);
ALTER TABLE public.user_roles ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);




CREATE TABLE public.roles (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT roles_name_key UNIQUE (name),
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);





CREATE TABLE public.audit_log (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"timestamp" timestamp(6) NULL,
	changes varchar(255) NULL,
	country varchar(255) NULL,
	entity varchar(255) NULL,
	entity_id varchar(255) NULL,
	ip_address varchar(255) NULL,
	operation varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);




CREATE TABLE public.activity_log (
	execution_time int8 NOT NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"timestamp" timestamp(6) NULL,
	activity varchar(255) NULL,
	client_type varchar(255) NULL,
	ip varchar(255) NULL,
	"method" varchar(255) NULL,
	outcome varchar(255) NULL,
	uri varchar(255) NULL,
	user_agent varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT activity_log_pkey PRIMARY KEY (id)
);