# version: '3.8'

# services:
#   postgres:
#     image: postgres:latest
#     container_name: immigration_visa_db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: root
#       POSTGRES_DB: "immigration-visa"
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./init:/docker-entrypoint-initdb.d # Mount the init directory for schema initialization


#   immigration-visa-service:
#     build: .
#     container_name: immigration_visa_service
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_PROFILES_ACTIVE: dev
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/immigration-visa
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: root
#       SPRING_JPA_HIBERNATE_DDL_AUTO: create
#     depends_on:
#       - postgres

# volumes:
#   pgdata:


  version: "3"
  services:
    spring:
      build: .
      container_name: immigration_visa_service
      environment:
        SPRING_PROFILES_ACTIVE: dev
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/immigration-visa
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_JPA_HIBERNATE_DDL_AUTO: create
      ports:
        - 8090:8090
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=immigration-visa
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./init:/docker-entrypoint-initdb.d 
      restart: always

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - 5050:80
  volumes:
    pgdata:
